

INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('SHOBHIT','PASSWORD');

INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('ABHISHEK','PASSWORD');

INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('EKANSH','PASSWORD');

INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('SATYA','PASSWORD');

INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('Aditya','PASSWORD');


INSERT INTO REGISTERED_SOCIETY_VOTERS  (
ADDRESS_LINE1, ADDRESS_LINE2, CASTED_VOTE, DISTRICT, EMAIL_ID, FIRST_NAME, GENDER, LAST_NAME, 
MANDAL, MOBILENO, PASSWORD, PINCODE, RESERVATION_CATEGORY, VOTER_ID_CARD_NO)
values('BTM', 'Banglore South', FALSE, 'Banglore', 'capg.kumar@email.com', 'Shobit', 'Male', 'Kumar', 'mondal', '8763326753', 
'paass', 560068, 'Gen', 'v45htes');