INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('SHOBHIT','PASSWORD');
INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('ABHISHEK','PASSWORD');
INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('EKANSH','PASSWORD');
-- id 1
INSERT INTO COOPERATIVE_SOCIETY  (DISTRICT ,HEAD_OF_SOCIETY ,MANDAL ,PINCODE ,SOCIETY_NAME ,VILLAGE )VALUES ('dIst', 'head','mandal',789456,'society a','village');


-- id 1
INSERT INTO REGISTERED_SOCIETY_VOTERS (ADDRESS ,CASTED_VOTE ,DISTRICT, EMAIL_ID,FIRST_NAME ,GENDER ,LAST_NAME ,MANDAL ,MOBILENO ,PINCODE ,RESERVATION_CATEGORY ,STATUS ,VOTER_ID_CARD_NO ,COOPERATIVE_SOCIETY_FK ) VALUES  ('BTM Layout', False, 'Banglore South', 'ritik.kumar@gmail.com', 'Ritik', 'Male', 'Kumar', 'BTM Mandal', '9938667700', 560068, 'gen', 'active', 'v72345', 1);

-- id 1
INSERT INTO NOMINATED_CANDIDATES (APPROVED_BY_ELECTION_OFFICER , NOMINATION_FORM_NO , OATH_OR_AFFIRMATION_SUMMITED , PARTY_NAME , POLICE_VERIFICATION_DONE , SECURITY_DEPOSIT , SYMBOL , COOPERATIVE_SOCIETY_FK , REGISTERED_SOCIETY_VOTER_FK )VALUES (False, 123,False, 'Party Name', False, 10000, 'sym', 1,1);

