INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('SHOBHIT','PASSWORD');
INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('ABHISHEK','PASSWORD');
INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('EKANSH','PASSWORD');
INSERT INTO ADMIN (ADMIN_NAME,ADMIN_PASSWORD)values('SATYA','PASSWORD');